version: '3.4'

services:
  s_apigateway:
    container_name: c_apigateway
    image: erhangocen/apigateway
    build:
      context: .
      dockerfile: src/APIGateway/Dockerfile
    networks:
      - net_api
      - int_net_api
    ports:
      - 80:80

  s_category_api:
    container_name: c_category_api
    image: erhangocen/category
    build:
      context: .
      dockerfile: src/category/Dockerfile
    networks:
      - int_net_api
    ports:
      - 9000:9000

  s_product_api:
    container_name: c_product_api
    image: erhangocen/product
    build:
      context: .
      dockerfile: src/product/Dockerfile
    networks:
      - int_net_api
    ports:
      - 9001:9001


networks:
  net_api:
    driver: bridge

  int_net_api:
    driver: overlay
    internal: true